Assignment 7 : CI/CD
honghyeong/MLOpsCurriculum pull request #12
Opened 2022-04-08 01:13 UTC by honghyeong

## Type of PR : [New Features, Fix, Structure changes, etc.]

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## Check List
- test.yml에서 unit testing을 작성할 때 build와 test를 구분해서 upload artifact, download artifact를 꼭 이용해야하나요? 테스팅 시간이 길어져서 일단 사용하지않았습니다 !
- Action을 사용할때 dependency 문제가 생겨서 Dockerfile 에서 yarn install --force, yarn install --save --legacy-peer-deps 옵션을 사용했는데, 혹시 나중에 문제가 될 수 있나요?

## Role of Reviewer

## Description
- .github/workflows/deploy.yml
- .github/workflows/deploy.yml

## TODO

2022-04-08 01:40 UTC, adldotori approved these changes
1. 정확히 이해하지는 못했는데 지금 코드로 하면 괜찮습니다.
2. dockerfile에는 따로 반영이 안된 것 같은데 맞나요? 제가 js는 잘 모르긴 한데 지금 docker 컨테이너 잘 실행되시면 큰 문제 없을 것 같습니다.

2022-04-08 01:40 UTC, adldotori commented on .github/workflows/deploy.yml
> +  #   branches: [main]
앗 이거 수정해주세용

2022-04-08 01:40 UTC, adldotori commented on .github/workflows/deploy.yml
> +          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
ECR 푸시 이후에 ECS로 배포까지 하는 것이 과제입니다!

2022-04-08 07:36 UTC, honghyeong commented on .github/workflows/deploy.yml
> +          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
@adldotori 태호님 ecs deploy 부분에서 task-definition.json 을 어떻게 해야할지 어렵습니다 ㅠ
혹시 docker compose up해서 생성된 서버랑 db 정의 참고해서 하셨나요 ??? ecs 콘솔로 일일이 설정해서 연결하고 생성된 작업정의 참고해서 하셨나요?

2022-04-09 04:33 UTC, adldotori requested changes

2022-04-09 04:33 UTC, adldotori commented on task-definition.json
> +          "value": "1234"
password 다 올라가서 task-definition.json을 따로 올리지 말고 git action 돌 때 다운받아서 사용하는 방법이 있습니다. https://docs.aws.amazon.com/cli/latest/reference/ecs/describe-task-definition.html 이 페이지 참고하세요.

2022-04-11 07:06 UTC, adldotori approved these changes
고생하셨어요!!

2022-04-11 07:06 UTC, merged