Feature/express api
honghyeong/MLOpsCurriculum pull request #5
Opened 2022-03-11 06:13 UTC by honghyeong

## Type of PR : [New Features, Fix, Structure changes, etc.]

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## Check List

## Role of Reviewer
- .gitignore에 넣어야할 정보가 무엇인지?
- code review
-
## Description
- ./routes/pg.js 파일이 postgresql과 연동하는 api 코드
- ./routes/memory.js 파일은 로컬 저장소 이용하여 api 설계 연습
-
## TODO

2022-03-14 07:52 UTC, adldotori requested changes

2022-03-14 07:52 UTC, adldotori commented on assignments/api-express/mlopsapi/routes/memory.js
> +  fs.readFile(__dirname + "/../data/user.json", "utf8", function (err, data) {
`/../data/user.json` 으로 하드코딩하기보다는 따로 환경변수나 파라미터로 지정해주면 더 좋겠습니다. 나중에 파일을 변경하게 되면 아래 데이터들 전부 수정해줘야 하니까요!

2022-03-14 07:52 UTC, adldotori commented on assignments/api-express/mlopsapi/routes/memory.js
> +router.post("/user/:id", function (req, res) {
API 명세보면 create할 때 id를 받지 않습니다!

2022-03-14 07:52 UTC, adldotori commented on assignments/api-express/mlopsapi/routes/memory.js
> +res.send();
제가 express 잘 몰라서 그런데 이거 여기에 있어도 괜찮나요...?

2022-03-14 07:52 UTC, adldotori commented on assignments/api-express/mlopsapi/routes/pg.js
> +  password: "mlopscur",
패스워드는 민감한 부분이므로 git에는 절대 올리면 안됩니다! user, host, database, port 도 올리지 않는 방향을 지향합니다.
배포하고 사용자가 쓰고 있는데 이 github을 보고 제가 해킹해서 모든 사용자 정보를 다 지워버릴 수도 있습니다.

이런 부분은 환경변수로 설정하면 좋습니다.

2022-03-14 07:52 UTC, adldotori commented on assignments/api-express/mlopsapi/routes/pg.js
> +  const query = new Query("SELECT * FROM users WHERE id=$1", [req.params.id]);
query 문에 사용자의 입력을 그대로 넣겠다는 것은 굉장히 위험한 발상입니다.
해당 쿼리에 id를 "1 or 1=1" 로 넣게 되면 SELECT * FROM users WHERE id=1 or 1=1 이 되어 모든 사용자의 정보가 전부 노출됩니다. SQL Injection 이라고 하는 기법인데 이를 피하기 위해서는 query 에 사용자의 입력을 그대로 넣는 것을 피해야 합니다.

query 가 아닌 ORM 을 써서 하는 방법을 찾아보면 좋겠습니다.
또한, 사용자의 입력은 어떠한 상황에서도 믿으시면 안됩니다. 개발할 때만큼은 성악설을 믿어야 해요.

2022-03-14 07:52 UTC, adldotori commented on assignments/api-express/mlopsapi/routes/pg.js
> +  if (!req.body.name || !req.body.age) {
이런 디테일한 예외처리와 메시지 너무 좋습니다.

2022-03-14 07:56 UTC, honghyeong commented on assignments/api-express/mlopsapi/routes/memory.js
> +router.post("/user/:id", function (req, res) {
이 부분은 로컬 json 파일을 DB로 이용할 때 id 자동 생성이 어려워서 넣었던 부분인데 pg.js 에서는 Postgresql의 create table SERIAL 이용해서 해결했습니다!

2022-03-14 07:57 UTC, honghyeong commented on assignments/api-express/mlopsapi/routes/memory.js
> +router.post("/user/:id", function (req, res) {
로컬 json을 이용해서 ID auto increment 하는 방법은 알아보고 수정하도록 하겠습니다! 피드백 감사하빈다

2022-03-14 08:06 UTC, honghyeong commented on assignments/api-express/mlopsapi/routes/pg.js
> +  password: "mlopscur",
다음에는 명세를 좀 더 확인하고 개발하도록 하겠습니다. 감사합니다!

2022-03-14 13:50 UTC, honghyeong commented on assignments/api-express/mlopsapi/routes/pg.js
> +  const query = new Query("SELECT * FROM users WHERE id=$1", [req.params.id]);
그렇네요. 예리한 지적 너무 감사합니다.

2022-03-15 05:29 UTC, merged

2022-03-17 07:25 UTC, hanchchch reviewed
뒤늦게 나마 리뷰 드립니다.

2022-03-17 07:25 UTC, hanchchch commented on assignments/api-express/mlopsapi/routes/memory.js
> +  var result = {};
var 금지입니다. let이나 const를 사용해주시고, const로 가능하면 const로 해주세요. var은 스코프가 모호해서 선언 순서와 사용 시점이 뒤죽박죽일 수 있습니다. 비직관적인 코딩이 가능해져서 이제 웬만하먼 legacy로 취급받습니다.

let과 const도, re-assign을 하지 않는 이상 const로 해주세요. 코딩중에 어떤 변수가 어떤 값인지 + 어떤 타입인지 명확하기 때문에 큰 도움이 됩니다. let은 re-assign이 불가피할때만 쓴다고 생각하시고, re-assign하실때도 처음 선언한 것과 같은 타입의 값으로 하시는게 좋습니다.

2022-03-17 07:25 UTC, hanchchch commented on assignments/api-express/mlopsapi/routes/memory.js
> +    if (!users[userid]) {
users.json을
```
{
  [id]: { ... }, 
}
```

이런 형식으로 하셨는데,

```
[
  { "id": [id], ... },
]
```

이런 리스트 형식으로 하시는 것을 추천드립니다.
일단 db에서 읽으면 table형식의 데이터이므로 이렇게 나오기 때문이기도 하고, 각 row마다 타입을 통일하기 위함이기도 합니다. id까지 리턴해줘야 할 때도 이 편이 더 편하구요.

2022-03-17 07:25 UTC, hanchchch commented on assignments/api-express/mlopsapi/routes/memory.js
> +    if (!users[userid]) {
그런다음 여기서는 `users.find((u) => u.id === userId)` 이런식으로 할 수 있겠습니다

2022-03-17 07:25 UTC, hanchchch commented on assignments/api-express/mlopsapi/routes/memory.js
> +    res.status(400).json({
이런 오류처리 하실 때 throw를 사용하시는 것을 더 추천합니다. 익셉션이 throw됐을 때 이를 캐치해서 알맞은 에러메세지를 응답으로 주는 기능이 express에 있습니다. exception filter에 대해서 찾아보세요.

throw를 하게 되면 함수 실행이 중단되므로 혹시 return을 까먹으셔도 문제가 생기지 않습니다. '오류'라는 맥락에도 더 맞구요. 에러 리턴 형식도 통일이 되고, 에러 메세지나 종류도 익셉션 클래스로 관리해서 더 체계적으로 될 수 있고요. 우리 레포 중에 nestjs로 만든 프로젝트에서 대부분 이렇게 하고 있는데 한번 확인해보시면 좋을 것 같아요!

2022-03-17 07:25 UTC, hanchchch commented on assignments/api-express/mlopsapi/routes/memory.js
> +      res.send(err.message);
res.send는 함수를 종료시키지 않으므로 return하셔야 합니다.
또 async 이므로 return하시더라도 아래코드가 실행될 수 있습니다. async, await를 이용해주시면 더 좋을 것 같습니다.

2022-03-17 07:25 UTC, hanchchch commented on assignments/api-express/mlopsapi/routes/pg.js
> +      res.send({ success: false, error: "No Users" });
보통 이런 경우에 그냥 빈 리스트를 리턴합니다. 유저가 없는게 잘못된 상황은 아니기 때문입니다. 또, 프론트엔드에서 처리할 때도 모든 응답이 리스트 형식임을 확실히 하고 개발할 수 있기 때문에 더 편합니다.

2022-03-17 07:25 UTC, hanchchch commented on assignments/api-express/mlopsapi/routes/pg.js
> +  const query = new Query("SELECT * FROM users WHERE id=$1", [req.params.id]);
그래서 사용자 입력을 validation하는 과정이 필요합니다. id는 숫자이므로 저라면Number(req.params.id) 이런 식으로 했을 것 같네요. 이 경우 이상한 값이 들어오면 NaN이 되고 이에 대한 예외처리만 해주면 됩니다(400).

2022-03-17 07:29 UTC, hanchchch commented
전체적인 구조에서도, routes에 모든 콜백 함수들을 같이 정의하는 것보다 MVC 패턴에 맞추어 컨트롤러, 서비스, 모델 나누어서 개발 하셨다면 더 좋았을 것 같습니다. 컨트롤러는 라우팅만 하고, 서비스는 모델(레포지토리)가 어떤 일을 수행하는지 모르는 상태로 인터페이스만 가지고 사용하고, 모델은 file과 pg로 나누어서 두 개의 레포지토리를 만들고요. 그러면 굳이 memory.js과 pg.js로 나누셔서 모든 걸 두 번 작성하실 필요가 없었을 것 같아요

2022-03-18 00:43 UTC, honghyeong commented on assignments/api-express/mlopsapi/routes/memory.js
> +  var result = {};
주의하겠습니다 !